### PR TITLE
Incorrect homebank transaction types

### LINKED ISSUE #21: Issue with DD in smile being translates to FI
It seems like DD's are being incorrectly translated to FI's.
* confirm that DD for those line are actually setup as DD's
*  decide what the correct conversion value should be
* update the tests

### PR DESCRIPTION
**Pull request by TimeBandit**
updated docs, fixed conversions mismatch, updated tests, closes #21

### CODE REVIEW

File: src/parser/strategies/smilebank-strategy.ts [hunk 1]
```diff
@@ -48,7 +41,7 @@ class SmileBankStrategy implements BaseStrategy {
         homeBankTransactionType = HomebankPaymentType.StandingOrder;
         break;
       case SmilePaymentType.Transfer:
-        homeBankTransactionType = HomebankPaymentType.Transfer;
+        homeBankTransactionType = HomebankPaymentType.ElectronicPayment;
```
Comment (TimeBandit) [inline src/parser/strategies/smilebank-strategy.ts:44]: looks better
